USE MASTER
GO

-- Drop database if it existed before:
IF DB_ID('QLBanHang') IS NOT NULL
	DROP DATABASE QLBanHang
GO

-- Create database QLBanHang:
CREATE DATABASE QLBanHang
GO

USE QLBanHang
GO

-- Create table NHAN_VIEN:
CREATE TABLE NHAN_VIEN(
	MaNV INT IDENTITY(1,1) PRIMARY KEY,
	TenNV NVARCHAR(30) NOT NULL,
	VaiTro NVARCHAR(15) NOT NULL,
	username nvarchar(15) NOT NULL,
	password nvarchar(100) NOT NULL
)
GO

-- Create table NHA_CUNG_CAP:
CREATE TABLE NHA_CUNG_CAP(
	MaNCC INT IDENTITY(1,1) PRIMARY KEY,
	TenNCC NVARCHAR(50) NOT NULL
)
GO

-- Create table MAT_HANG:
CREATE TABLE MAT_HANG(
	MaMH INT IDENTITY(1,1) PRIMARY KEY,
	TenMH NVARCHAR(50) NOT NULL,
	SoLuongTon INT NOT NULL, CHECK(SoLuongTon >= 0),
	SoLuongTraLai INT NOT NULL, CHECK(SoLuongTraLai >= 0),
	LoaiMatHang NVARCHAR(20) NOT NULL,
	DonGia MONEY NOT NULL,
	NVQL INT,
	MaNCC INT,
	TrangThai BIT
)
GO

-- Create table DOI_TAC_QC:
CREATE TABLE DOI_TAC_QC(
	MaDoiTac INT IDENTITY(1,1) PRIMARY KEY,
	TenDoiTac NVARCHAR(50) NOT NULL,
	NgayKiHD DATETIME NOT NULL,
	ThoiHan INT NOT NULL,
	ThongTinViTriDang NVARCHAR(50) NOT NULL
)
GO

-- Create table DTQC_MH:
CREATE TABLE DTQC_MH(
	MaDT INT,
	MaMH INT,
	NgayDangQC DATETIME NOT NULL,
	CONSTRAINT PK_DTQC_MH PRIMARY KEY (MaDT,MaMH,NgayDangQC)
)
GO

-- Create table HOP_DONG:
CREATE TABLE HOP_DONG(
	MaHopDong INT IDENTITY(1,1) PRIMARY KEY,
	ThoiGianLap DATETIME NOT NULL,
	MaDT INT NOT NULL,
	ThoiHan INT NOT NULL,
	MaNV INT NOT NULL
)
GO

-- Create table COMMENT_MH:
CREATE TABLE COMMENT_MH(
	MaCMT INT IDENTITY(1,1) PRIMARY KEY,
	Email VARCHAR(30) NOT NULL,
	MaMH INT NOT NULL,
	NhanXet NVARCHAR(60) NOT NULL,
	LoaiComment BIT DEFAULT NULL,
)
GO

-- Create table KH_COMMENT:
CREATE TABLE KH_COMMENT(
	Email VARCHAR(30) PRIMARY KEY,
	HoTen NVARCHAR(30) NOT NULL,
	DiaChi NVARCHAR(50) NOT NULL,
	BiCamCmt BIT DEFAULT NULL
)
GO

-- Create table QUA_TANG:
CREATE TABLE QUA_TANG(
	MaQuaTang INT IDENTITY(1,1) PRIMARY KEY,
	TenQuaTang NVARCHAR(50) NOT NULL,
	GiaTri MONEY NOT NULL,
)
GO

-- Create table DANH_SACH_QUA_TANG:
CREATE TABLE DANH_SACH_QUA_TANG(
	Email VARCHAR(30),
	MaMH INT,
	MaQT INT ,
	SoLuong INT NOT NULL,

	CONSTRAINT PK_DSQT PRIMARY KEY (Email,MaMH,MaQT)
)
GO

-- Create table DON_TRA_HANG:
CREATE TABLE DON_TRA_HANG(
	MaDonTra INT IDENTITY(1,1) PRIMARY KEY,
	NgayLap DATETIME NOT NULL,
	NVLap INT,
)
GO

-- Create table CHI_TIET_DTH:
CREATE TABLE CHI_TIET_DTH(
	MaDT INT,
	MaMH INT,
	SoLuong INT NOT NULL,
	LyDo NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_CHI_TIET_DTH PRIMARY KEY(MaDT,MaMH)
)
GO

-- Create table DON_NHAP_HANG:
CREATE TABLE DON_NHAP_HANG(
	MaDonNhap INT IDENTITY(1,1) PRIMARY KEY,
	NVLapDon INT NOT NULL,
	SoLuong INT NOT NULL,
	MaNCC INT NOT NULL,
	TrangThaiDuyet NVARCHAR(50) NOT NULL,
	NgayLap DATETIME NOT NULL,
	NgayNhap DATETIME NULL,
	NVNhapHang INT NULL
)
GO

-- Create table CHI_TIET_DNH:
CREATE TABLE CHI_TIET_DNH(
	MaDonNhap INT,
	MaMH INT,
	SoLuong INT NOT NULL,

	CONSTRAINT PK_CT_DNH PRIMARY KEY(MaDonNhap,MaMH)
)
GO

-- Create table KHACH_HANG:
CREATE TABLE KHACH_HANG(
	MaKH INT IDENTITY(1,1) PRIMARY KEY,
	TenKH NVARCHAR(30) NOT NULL,
	SDT VARCHAR(15) NOT NULL,
	DiaChi NVARCHAR(50) NOT NULL,
	Email VARCHAR(30) NOT NULL,
)
GO

-- Create table TIN_NHAN_DA_GUI:
CREATE TABLE TIN_NHAN_DA_GUI(
	MaKH INT,
	MaMH INT,
	NgayGui DATETIME NOT NULL,
	NVGui INT NOT NULL,
	CONSTRAINT PK_MSG PRIMARY KEY(MaKH,MaMH)
)
GO

-- Create table HOA_DON:
CREATE TABLE HOA_DON(
	MaHD INT IDENTITY(1,1) PRIMARY KEY,
	MaKH INT NOT NULL,
	TrangThaiHD NVARCHAR(50) NULL,
	NVGiaoHang INT NULL,
	NVBanHang INT NOT NULL ,
	HinhThucThanhToan INT NOT NULL,
	TongTien Money NOT NULL
)
GO

-- Create table CHI_TIET_DON_HANG:
CREATE TABLE CHI_TIET_DON_HANG(
	MaHD INT,
	MaMH INT,
	SoLuong INT NOT NULL,
	ThanhTien MONEY NOT NULL,
	CONSTRAINT PK_CT_DH PRIMARY KEY(MaHD, MaMH)
)
GO

-- Create table HOA_DON_TT_THE:
CREATE TABLE HOA_DON_TT_THE(
	MaHD INT PRIMARY KEY,
	HinhThucThanhToan NVARCHAR(50),
	MaGiaoDich NVARCHAR(50)
)
GO

-- Create table PHIEU_TRA_HANG:
CREATE TABLE PHIEU_TRA_HANG(
	MaHD INT,
	MaMH INT,
	SoLuong INT,
	LyDo NVARCHAR(50),
	SoTienHoanTra MONEY

	CONSTRAINT PK_PTH PRIMARY KEY(MaHD, MaMH)
)
GO

-- Create FK constraints:
ALTER TABLE MAT_HANG ADD CONSTRAINT FK_MH_NCC FOREIGN KEY(MaNCC) REFERENCES NHA_CUNG_CAP(MaNCC)
ALTER TABLE MAT_HANG ADD CONSTRAINT FK_MH_NV FOREIGN KEY(NVQL) REFERENCES NHAN_VIEN(MaNV)
ALTER TABLE DTQC_MH ADD CONSTRAINT FK_DTQC_MH FOREIGN KEY(MaMH) REFERENCES MAT_HANG(MaMH)
ALTER TABLE DTQC_MH ADD CONSTRAINT FK_DTQC_DT FOREIGN KEY(MaDT) REFERENCES DOI_TAC_QC(MaDoiTac)
ALTER TABLE HOP_DONG ADD CONSTRAINT FK_HD_DT FOREIGN KEY(MaDT) REFERENCES DOI_TAC_QC(MaDoiTac)
ALTER TABLE HOP_DONG ADD CONSTRAINT FK_HD_NV FOREIGN KEY(MaNV) REFERENCES NHAN_VIEN(MaNV)
ALTER TABLE COMMENT_MH ADD CONSTRAINT FK_CMT_KH FOREIGN KEY(MaMH) REFERENCES MAT_HANG(MaMH)
ALTER TABLE COMMENT_MH ADD CONSTRAINT FK_CMT_TTKH FOREIGN KEY(Email) REFERENCES KH_COMMENT(Email)
ALTER TABLE DANH_SACH_QUA_TANG ADD CONSTRAINT FK_DSQT_CMT FOREIGN KEY(Email) REFERENCES KH_COMMENT(Email)
ALTER TABLE DANH_SACH_QUA_TANG ADD CONSTRAINT FK_DSQT_QT FOREIGN KEY(MaQT) REFERENCES QUA_TANG(MaQuaTang) 
ALTER TABLE DON_TRA_HANG ADD CONSTRAINT FK_DTH_NV FOREIGN KEY(NVLap) REFERENCES NHAN_VIEN(MaNV)
ALTER TABLE CHI_TIET_DTH ADD CONSTRAINT FK_CTDTH_DTH FOREIGN KEY(MaDT) REFERENCES DON_TRA_HANG(MaDonTra)
ALTER TABLE CHI_TIET_DTH ADD CONSTRAINT FK_CTDTH_MH FOREIGN KEY(MaMH) REFERENCES MAT_HANG(MaMH)
ALTER TABLE DON_NHAP_HANG ADD CONSTRAINT FK_DNH_NVLD FOREIGN KEY(NVLapDon) REFERENCES NHAN_VIEN(MaNV)
ALTER TABLE DON_NHAP_HANG ADD CONSTRAINT FK_DNH_NCC FOREIGN KEY(MaNCC) REFERENCES NHA_CUNG_CAP(MaNCC)
ALTER TABLE DON_NHAP_HANG ADD CONSTRAINT FK_DNH_NVNH FOREIGN KEY(NVNhapHang) REFERENCES NHAN_VIEN(MaNV)
ALTER TABLE CHI_TIET_DNH ADD CONSTRAINT FK_CTDNH_DNH FOREIGN KEY(MaDonNhap) REFERENCES DON_NHAP_HANG(MaDonNhap)
ALTER TABLE CHI_TIET_DNH ADD CONSTRAINT FK_CTDNH_MH FOREIGN KEY(MaMH) REFERENCES MAT_HANG(MaMH)
ALTER TABLE TIN_NHAN_DA_GUI ADD CONSTRAINT FK_MSG_KH FOREIGN KEY(MaKH) REFERENCES KHACH_HANG(MaKH)
ALTER TABLE TIN_NHAN_DA_GUI ADD CONSTRAINT FK_MSG_MH FOREIGN KEY(MaMH) REFERENCES MAT_HANG(MaMH)
ALTER TABLE TIN_NHAN_DA_GUI ADD CONSTRAINT FK_MSG_NV FOREIGN KEY(NVGui) REFERENCES NHAN_VIEN(MaNV)
ALTER TABLE HOA_DON ADD CONSTRAINT FK_HD_KH FOREIGN KEY(MaKH) REFERENCES KHACH_HANG(MaKH)
ALTER TABLE HOA_DON ADD CONSTRAINT FK_HD_NVGH FOREIGN KEY(NVGiaoHang) REFERENCES NHAN_VIEN(MaNV)
ALTER TABLE HOA_DON ADD CONSTRAINT FK_HD_NVBH FOREIGN KEY(NVBanHang) REFERENCES NHAN_VIEN(MaNV)
ALTER TABLE CHI_TIET_DON_HANG ADD CONSTRAINT FK_CTDH_HD FOREIGN KEY(MaHD) REFERENCES HOA_DON(MaHD)
ALTER TABLE CHI_TIET_DON_HANG ADD CONSTRAINT FK_CTDH_MH FOREIGN KEY(MaMH) REFERENCES MAT_HANG(MaMH)
ALTER TABLE HOA_DON_TT_THE ADD CONSTRAINT FK_HDTTT_HD FOREIGN KEY(MaHD) REFERENCES HOA_DON(MaHD)
ALTER TABLE PHIEU_TRA_HANG ADD CONSTRAINT FK_PTH_HD FOREIGN KEY(MaHD) REFERENCES HOA_DON(MaHD)
ALTER TABLE PHIEU_TRA_HANG ADD CONSTRAINT FK_PTH_MH FOREIGN KEY(MaMH) REFERENCES MAT_HANG(MaMH)

-- Create data:

INSERT INTO NHAN_VIEN VALUES(N'Nguyễn Văn Toàn',N'Quản lí','nhanvien1','$2a$10$0mwsqyrAm0i9faDvkZlxAOBAUWKFVzYBQ.V3SpRh77Zrqp1sXD2g2')
INSERT INTO NHAN_VIEN VALUES(N'Trần Tấn Tài',N'NV Bán hàng','nhanvien2','$2a$10$0mwsqyrAm0i9faDvkZlxAOBAUWKFVzYBQ.V3SpRh77Zrqp1sXD2g2')
INSERT INTO NHAN_VIEN VALUES(N'Nguyễn Thị Thanh Hương',N'NV Bán hàng','nhanvien3','$2a$10$0mwsqyrAm0i9faDvkZlxAOBAUWKFVzYBQ.V3SpRh77Zrqp1sXD2g2')
INSERT INTO NHAN_VIEN VALUES(N'Nguyễn Thị Ánh Viên',N'NV Bán hàng','nhanvien4','$2a$10$0mwsqyrAm0i9faDvkZlxAOBAUWKFVzYBQ.V3SpRh77Zrqp1sXD2g2')
INSERT INTO NHAN_VIEN VALUES(N'Nguyễn Thị Oanh',N'NV Bán hàng','nhanvien5','$2a$10$0mwsqyrAm0i9faDvkZlxAOBAUWKFVzYBQ.V3SpRh77Zrqp1sXD2g2')
INSERT INTO NHAN_VIEN VALUES(N'Hồ Khắc Ngọc',N'NV Bán hàng','nhanvien6','$2a$10$0mwsqyrAm0i9faDvkZlxAOBAUWKFVzYBQ.V3SpRh77Zrqp1sXD2g2')
INSERT INTO NHAN_VIEN VALUES(N'Nguyễn Hải Huy',N'NV Bán hàng','nhanvien7','$2a$10$0mwsqyrAm0i9faDvkZlxAOBAUWKFVzYBQ.V3SpRh77Zrqp1sXD2g2')
INSERT INTO NHAN_VIEN VALUES(N'Võ Huy Toàn',N'NV Giao hàng','nhanvien8','$2a$10$0mwsqyrAm0i9faDvkZlxAOBAUWKFVzYBQ.V3SpRh77Zrqp1sXD2g2')
INSERT INTO NHAN_VIEN VALUES(N'Nguyễn Thị Tuyết Dung',N'NV Giao hàng','nhanvien9','$2a$10$0mwsqyrAm0i9faDvkZlxAOBAUWKFVzYBQ.V3SpRh77Zrqp1sXD2g2')
INSERT INTO NHAN_VIEN VALUES(N'Quách Thị Lan',N'NV Giao hàng','nhanvien10','$2a$10$0mwsqyrAm0i9faDvkZlxAOBAUWKFVzYBQ.V3SpRh77Zrqp1sXD2g2')
INSERT INTO NHAN_VIEN VALUES(N'Trần Thị Kim Thanh',N'NV Giao hàng','nhanvien11','$2a$10$0mwsqyrAm0i9faDvkZlxAOBAUWKFVzYBQ.V3SpRh77Zrqp1sXD2g2')
INSERT INTO NHAN_VIEN VALUES(N'Mạc Hồng Quân',N'NV Giao hàng','nhanvien12','$2a$10$0mwsqyrAm0i9faDvkZlxAOBAUWKFVzYBQ.V3SpRh77Zrqp1sXD2g2')
INSERT INTO NHAN_VIEN VALUES(N'Lê Ngọc Bảo',N'NV Giao hàng','nhanvien13','$2a$10$0mwsqyrAm0i9faDvkZlxAOBAUWKFVzYBQ.V3SpRh77Zrqp1sXD2g2')
INSERT INTO NHAN_VIEN VALUES(N'Nguyễn Hoàng Đức',N'Quản lý','nhanvien14','$2a$10$0mwsqyrAm0i9faDvkZlxAOBAUWKFVzYBQ.V3SpRh77Zrqp1sXD2g2')
INSERT INTO NHAN_VIEN VALUES(N'Huỳnh Tấn Sinh',N'NV Đăng tin','nhanvien15','$2a$10$0mwsqyrAm0i9faDvkZlxAOBAUWKFVzYBQ.V3SpRh77Zrqp1sXD2g2')
INSERT INTO NHAN_VIEN VALUES(N'Triệu Việt Hưng',N'NV Đăng tin','nhanvien16','$2a$10$0mwsqyrAm0i9faDvkZlxAOBAUWKFVzYBQ.V3SpRh77Zrqp1sXD2g2')
INSERT INTO NHAN_VIEN VALUES(N'Nguyễn Thanh Thịnh ',N'NV Đăng tin','nhanvien17','$2a$10$0mwsqyrAm0i9faDvkZlxAOBAUWKFVzYBQ.V3SpRh77Zrqp1sXD2g2')
INSERT INTO NHAN_VIEN VALUES(N'Huỳnh Tuấn Linh',N'NV Đăng tin','nhanvien18','$2a$10$0mwsqyrAm0i9faDvkZlxAOBAUWKFVzYBQ.V3SpRh77Zrqp1sXD2g2')
INSERT INTO NHAN_VIEN VALUES(N'Mai Xuân Quyết',N'Thủ quỹ','nhanvien19','$2a$10$0mwsqyrAm0i9faDvkZlxAOBAUWKFVzYBQ.V3SpRh77Zrqp1sXD2g2')
INSERT INTO NHAN_VIEN VALUES(N'Tô Văn Vũ',N'Thủ quỹ','nhanvien20','$2a$10$0mwsqyrAm0i9faDvkZlxAOBAUWKFVzYBQ.V3SpRh77Zrqp1sXD2g2')

INSERT INTO NHA_CUNG_CAP VALUES(N'Cty TNHH MTV ABC')
INSERT INTO NHA_CUNG_CAP VALUES(N'Cty TNHH MTV Aeon')
INSERT INTO NHA_CUNG_CAP VALUES(N'Cty TNHH MTV Vĩnh Phát')
INSERT INTO NHA_CUNG_CAP VALUES(N'Cty TNHH MTV Hùng Thịnh')
INSERT INTO NHA_CUNG_CAP VALUES(N'Cty TNHH Tài Phát')
INSERT INTO NHA_CUNG_CAP VALUES(N'Cty TNHH MTV Techzone')
INSERT INTO NHA_CUNG_CAP VALUES(N'Cty TNHH MTV An Phát')
INSERT INTO NHA_CUNG_CAP VALUES(N'Cty TNHH MTV Hữu Thịnh')
INSERT INTO NHA_CUNG_CAP VALUES(N'Cty TNHH MTV Phước Đạt')
INSERT INTO NHA_CUNG_CAP VALUES(N'Cty TNHH MTV Hữu Hảo')

INSERT INTO MAT_HANG VALUES(N'Nước giặt Omo Matic',100,20,N'Nước giặt',15000,5,1,1)
INSERT INTO MAT_HANG VALUES(N'Nước giặt Aba',100,30,N'Nước giặt',20000,1,3,0)
INSERT INTO MAT_HANG VALUES(N'Nước giặt Clean',100,40,N'Nước giặt',150000,1,4,0)
INSERT INTO MAT_HANG VALUES(N'Nước giặt Ariel',100,10,N'Nước giặt',150000,1,5,0)
INSERT INTO MAT_HANG VALUES(N'Nước giặt Comfort',100,5,N'Nước giặt',150000,5,1,0)
INSERT INTO MAT_HANG VALUES(N'Nước rửa chén Sunlight',100,25,N'Nước rửa chén',150000,5,2,0)
INSERT INTO MAT_HANG VALUES(N'Nước rửa chén Mỹ Hảo',100,30,N'Nước rửa chén',150000,4,2,0)
INSERT INTO MAT_HANG VALUES(N'Nước rửa chén Vidan',20,15,N'Nước rửa chén',150000,5,2,0)
INSERT INTO MAT_HANG VALUES(N'Bột giặt Suft',30,10,N'Bột giặt',12000,4,2,0)
INSERT INTO MAT_HANG VALUES(N'Bột giặt Omo',10,10,N'Bột giặt',10000,5,3,0)

INSERT INTO KHACH_HANG VALUES(N'Nguyễn Văn A',0858314105,N'50 Hoàng Huy Giáp','nguyena@gmail.com');
INSERT INTO KHACH_HANG VALUES(N'Hoàng Văn B',0123456789,N'51 Hoàng Huy Giáp','vanb@gmail.com');
INSERT INTO KHACH_HANG VALUES(N'Trần Văn C',0123456788,N'52 Hoàng Huy Giáp','tranc@gmail.com');

INSERT INTO HOA_DON VALUES(1,N'Đã thanh toán',5,12,1,200000)
INSERT INTO HOA_DON VALUES(2,N'Đã thanh toán',5,13,2,300000)
INSERT INTO HOA_DON VALUES(3,N'Đã thanh toán',5,12,1,400000)
INSERT INTO HOA_DON VALUES(1,N'Đã thanh toán',5,13,2,200000)
INSERT INTO HOA_DON VALUES(2,N'Chưa thanh toán',6,12,0,300000)
INSERT INTO HOA_DON VALUES(3,N'Chưa thanh toán',6,13,0,400000)
INSERT INTO HOA_DON VALUES(1,N'Chưa thanh toán',6,12,0,200000)
INSERT INTO HOA_DON VALUES(2,N'Chưa thanh toán',6,13,0,300000)

INSERT INTO CHI_TIET_DON_HANG VALUES(1,1,10,150000);
INSERT INTO CHI_TIET_DON_HANG VALUES(1,2,5,100000);
INSERT INTO CHI_TIET_DON_HANG VALUES(2,1,5,75000);
INSERT INTO CHI_TIET_DON_HANG VALUES(2,3,2,100000);
INSERT INTO CHI_TIET_DON_HANG VALUES(3,2,10,400000);
INSERT INTO CHI_TIET_DON_HANG VALUES(3,4,12,100000);
INSERT INTO CHI_TIET_DON_HANG VALUES(3,5,10,100000);
INSERT INTO CHI_TIET_DON_HANG VALUES(4,6,12,120000);
INSERT INTO CHI_TIET_DON_HANG VALUES(5,7,20,200000);

INSERT INTO PHIEU_TRA_HANG VALUES(1,1,7,N'Hàng lỗi',105000);
INSERT INTO PHIEU_TRA_HANG VALUES(2,1,3,N'Hàng lỗi',45000);
INSERT INTO PHIEU_TRA_HANG VALUES(3,2,10,N'Hàng lỗi',400000);
INSERT INTO PHIEU_TRA_HANG VALUES(3,4,12,N'Hàng lỗi',100000);
INSERT INTO PHIEU_TRA_HANG VALUES(3,5,10,N'Hàng lỗi',100000);
INSERT INTO PHIEU_TRA_HANG VALUES(4,6,12,N'Hàng lỗi',120000);
INSERT INTO PHIEU_TRA_HANG VALUES(5,7,20,N'Hàng lỗi',200000);

INSERT INTO DON_TRA_HANG VALUES('2020-05-20',5);

INSERT INTO HOA_DON_TT_THE VALUES(2,N'Momo','MM1234');
INSERT INTO HOA_DON_TT_THE VALUES(4,N'ZaloPay','ZL01512');


INSERT INTO DOI_TAC_QC VALUES('Super Corp','2020-02-04',2,'Quậna 1')
INSERT INTO DOI_TAC_QC VALUES('AdvertiseKing','2020-03-10',2,'Quận 2')
INSERT INTO DOI_TAC_QC VALUES('Project Creative','2020-06-24',2,'Quận 3')
INSERT INTO DOI_TAC_QC VALUES('Market Leader','2020-07-12',2,'Quận 4')

INSERT INTO DTQC_MH VALUES(1,1,GETDATE())

insert into KH_COMMENT values('hoahong@gmail.com',N'Nguyễn Văn A',N'Ho Chi Minh',0);
insert into KH_COMMENT values('hoahue@gmail.com',N'Nguyễn Văn B',N'Ho Chi Minh',0);
insert into KH_COMMENT values('hoalan@gmail.com',N'Nguyễn Văn C',N'Ho Chi Minh',0);
insert into KH_COMMENT values('hoahoe@gmail.com',N'Nguyễn Văn D',N'Ho Chi Minh',0);

insert into COMMENT_MH values('hoahong@gmail.com',1,N'hehe',NULL);
insert into COMMENT_MH values('hoahue@gmail.com',2,N'hahaha',NULL);
insert into COMMENT_MH values('hoalan@gmail.com',1,N'hihihi',NULL);

select* from MAT_HANG;